dialect "mvel"

import com.diviso.graeshoppe.offer.model.OrderModel;
import com.diviso.graeshoppe.offer.domain.OrderRule;
import com.diviso.graeshoppe.offer.domain.DeductionValueType;
import com.diviso.graeshoppe.offer.domain.PriceRule;
 
 rule "Offer for first and every 10th order"
	no-loop
	when 
		$orderModel : OrderModel() 
		$orderRule : OrderRule(($orderModel.getOrderNumber() % $orderRule.getPrerequisiteOrderNumber())==0 || $orderModel.getOrderNumber()==1 )
		$deductionValueType : DeductionValueType(getDeductionValueType()=='Percentage')
		$priceRule : PriceRule(getStartDate() < $orderModel.getClaimedDate(),getEndDate() > $orderModel.getClaimedDate());
 	then
 		modify($orderModel){
  	  		setRuleDiscountAmount(($priceRule.getDeductionValue()*$orderModel.getOrderTotal())/100);
  	  	}
  	  	 System.out.println("in drools else condition");
  	  	
 end
 
 rule "% off on Selected Days"
	no-loop
	when 
		$orderModel : OrderModel() 
		$orderRule : OrderRule(($orderModel.getOrderNumber() % $orderRule.getPrerequisiteOrderNumber())==0 || $orderModel.getOrderNumber()==1 )
		$deductionValueType : DeductionValueType(getDeductionValueType()=='Percentage')
		$priceRule : PriceRule(getStartDate() < $orderModel.getClaimedDate(),getEndDate() > $orderModel.getClaimedDate());
 	then
 		modify($orderModel){
  	  		setRuleDiscountAmount(($priceRule.getDeductionValue()*$orderModel.getOrderTotal())/100);
  	  	}
  	  	 System.out.println("in drools else condition");
  	  	
 end